mod_version=1.0.0
mod_group_id=com.liksus.kicraft
mod_id=kicraft
mod_authors=Liksus
mapping_channel=official
mapping_version=1.20.1
mod_name=Kicraft
mod_license=MIT
mod_description=Piccolo is here
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.1.0
forge_version_range=[47,)
loader_version_range=[47,)